# TensorFlow Ops!

Adapted from [CS 20: Tensorflow for Deep Learning Research](http://web.stanford.edu/class/cs20si/syllabus.html)

CS 20: TensorFlow for Deep Learning Research  
Lecture 2  
1/17/2017

## Agenda

Basic operations  
Tensor types  
Importing data  
Lazy loading  
Fun with TensorBoard!!!  

## Your first TensorFlow program

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # No more warning
import tensorflow as tf

In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
     print(sess.run(x))

5


Warning?
The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.

In [3]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
     print(sess.run(x))

5


## Visualize it with TensorBoard

In [4]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
# Create the summary writer after graph definition and before running your session 
# add the following line to use TensorBoard.
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
#     writer = tf.summary.FileWriter("./graphs", sess.graph) 
    print(sess.run(x))
writer.close() # close the writer when you’re done using it

5


## Run it

Go to terminal, run:  
$ python [yourprogram].py   

$ tensorboard --logdir="./graphs" --port 6006  
Then open your browser and go to: http://localhost:6006/

**Learn to use TensorBoard well and often.
It will help a lot when you build complicated models.**

**Question: How to change Const, Const_1 to the names we give the variables?**

##  Explicitly name them

In [5]:
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
writer.close() 

5


**TensorBoard can do much more than just visualizing your graphs. Learn to use TensorBoard well and often!**

##  Constants, Sequences, Variables, Ops

## Constants

**tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)**

**Broadcasting similar to NumPy**

In [6]:
a = tf.constant([2, 4], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
with tf.Session() as sess:
     x, y = sess.run([x, y])
     print("x equals to: \n", x)
     print("y equals to: \n", y)

x equals to: 
 [[2 5]
 [4 7]]
y equals to: 
 [[ 0  4]
 [ 4 12]]


### Tensors filled with a specific value

**tf.zeros(shape, dtype=tf.float32, name=None)**  
creates a tensor of shape and all elements will be zeros (when ran in session)

**Similar to numpy.zeros**

In [7]:
tf.zeros([2, 3], tf.int32) 

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [8]:
with tf.Session() as sess:
    print(sess.run(tf.zeros([2, 3], tf.int32)))

[[0 0 0]
 [0 0 0]]


In [9]:
a=tf.zeros([2, 3], tf.int32)
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[[0 0 0]
 [0 0 0]]


**tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)**  
creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.

In [10]:
input_tensor=tf.constant([[0, 1], [2, 3], [4, 5]])
output_tensor=tf.zeros_like(input_tensor)
with tf.Session() as sess:
    input_tensor=sess.run(input_tensor)
    output_tensor=sess.run(output_tensor)
print("input_tensor equals to \n", input_tensor)
print("output_tensor equals to \n", output_tensor)

input_tensor equals to 
 [[0 1]
 [2 3]
 [4 5]]
output_tensor equals to 
 [[0 0]
 [0 0]
 [0 0]]


### Tensors filled with a specific value

**tf.ones(shape, dtype=tf.float32, name=None)**  
**tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)**

In [11]:
a=tf.ones([4, 3], tf.int32)
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
input_tensor=tf.constant([[0, 1], [2, 3], [4, 5]])
output_tensor=tf.ones_like(input_tensor)
with tf.Session() as sess:
    input_tensor=sess.run(input_tensor)
    output_tensor=sess.run(output_tensor)
print("input_tensor equals to:\n", input_tensor)
print("output_tensor equals to:\n", output_tensor)

input_tensor equals to:
 [[0 1]
 [2 3]
 [4 5]]
output_tensor equals to:
 [[1 1]
 [1 1]
 [1 1]]


###  Tensors filled with a specific value  
**tf.fill(dims, value, name=None)**  
creates a tensor filled with a scalar value.

In [13]:
a=tf.fill([2, 3], 8) 
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[[8 8 8]
 [8 8 8]]


## Constants as sequences

In [14]:
# tf.linspace(start, stop, num, name=None)  slightly different from np.linspace
a=tf.linspace(10.0, 13.0, 4)
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[10. 11. 12. 13.]


In [15]:
# tf.range(start, limit=None, delta=1, dtype=None, name='range')
a=tf.range(3, 18, 3) 
# 'start' is 3, 'limit' is 18, 'delta' is 3
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[ 3  6  9 12 15]


In [16]:
a=tf.range(5) 
# 'limit' is 5
with tf.Session() as sess:
    a=sess.run(a)
print(a)

[0 1 2 3 4]


**Note: NOT THE SAME AS NUMPY SEQUENCES**  
**Note: Tensor objects are not iterable**

In [17]:
# Raise an Error if you run the following code:
# for _ in tf.range(4):
#     print("test")

## Randomly Generated Constants

**tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)**  
**tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None,
name=None)**  
**tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None,
name=None)**  
**tf.random_shuffle(value, seed=None, name=None)**  
**tf.random_crop(value, size, seed=None, name=None)**  
**tf.multinomial(logits, num_samples, seed=None, name=None)**  
**tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)**

###  tf.set_random_seed(seed)

Sets the graph-level random seed for the default graph.

## Operations

**Pretty Standard, quite similar to numpy**  
**See TensorFlow documentation** 

In [18]:
a = tf.constant([3, 6])
b = tf.constant([2, 2]) 

In [19]:
output=tf.add(a, b) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[5 8]


In [20]:
output=tf.add_n([a, b, b])
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[ 7 10]


In [21]:
output=tf.multiply(a, b) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[ 6 12]


In [22]:
# Raise an Error if you run the following code:
# output=tf.matmul(a, b)
# with tf.Session() as sess:
#     output=sess.run(output)
# print(output)

In [23]:
output=tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1]))
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[[18]]


In [24]:
output=tf.divide(a, b) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[1.5 3. ]


In [25]:
output=tf.mod(a, b) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[1 0]


### Wizard of Div

In [26]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
     print("tf.divide(b, a) equals to: \n", sess.run(tf.divide(b, a)))
     print("tf.truediv(b, a) equals to: \n", sess.run(tf.truediv(b, a)))
     print("tf.floordiv(b, a) equals to: \n", sess.run(tf.floordiv(b, a)))
#      print(".realdiv(b, a) equals to: \n", sess.run(tf.realdiv(b, a)))  Error: only works for real values
     print("tf.truncateddiv(b, a) equals to: \n", sess.run(tf.truncatediv(b, a)))
     print("tf.floor_div(b, a) equals to: \n", sess.run(tf.floor_div(b, a)))

tf.divide(b, a) equals to: 
 [[0.  0.5]
 [1.  1.5]]
tf.truediv(b, a) equals to: 
 [[0.  0.5]
 [1.  1.5]]
tf.floordiv(b, a) equals to: 
 [[0 0]
 [1 1]]
tf.truncateddiv(b, a) equals to: 
 [[0 0]
 [1 1]]
tf.floor_div(b, a) equals to: 
 [[0 0]
 [1 1]]


##  TensorFlow Data Types

**TensorFlow takes Python natives types: boolean, numeric (int, float), strings**

In [27]:
# 0-d tensor, or "scalar"
t_0 = 19
tf.zeros_like(t_0) 

<tf.Tensor 'zeros_like_1:0' shape=() dtype=int32>

In [28]:
tf.ones_like(t_0) 

<tf.Tensor 'ones_like_1:0' shape=() dtype=int32>

In [29]:
# 1-d tensor, or "vector"
t_1 = ['apple', 'peach', 'grape']
output=tf.zeros_like(t_1) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[b'' b'' b'']


In [30]:
# # Raise an Error if you run the following code:
# output=tf.ones_like(t_1) 
# with tf.Session() as sess:
#     output=sess.run(output)
# print(output)

In [31]:
# 2x2 tensor, or "matrix"
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]]

In [32]:
output=tf.zeros_like(t_2) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[[False False False]
 [False False False]
 [False False False]]


In [33]:
output=tf.ones_like(t_2) 
with tf.Session() as sess:
    output=sess.run(output)
print(output)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## TensorFlow Data Types

### TF VS NP Data Types

**TensorFlow integrates seamlessly with NumPy**

In [34]:
import numpy as np
tf.int32 == np.int32

True

**Can pass numpy types to TensorFlow ops?**

In [35]:
tf.ones([2, 2], np.float32) 

<tf.Tensor 'ones_1:0' shape=(2, 2) dtype=float32>

**For tf.Session.run(fetches): if the requested fetch is a Tensor , output will be a NumPy ndarray.**

In [36]:
sess = tf.Session()
a = tf.zeros([2, 3], np.int32)
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>


In [37]:
# a = sess.run(a)  # Avoid doing this. Use a_out = sess.run(a)
a_out = sess.run(a)  
print(type(a_out )) 
sess.close

<class 'numpy.ndarray'>


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x12e0337b8>>

* Python native types: TensorFlow has to infer Python type
* NumPy arrays: NumPy is not GPU compatible

### What’s wrong with constants ...

* ... other than being constant?
* Constants are stored in the graph definition

## Print out the graph def

In [38]:
# my_const = tf.constant([1.0, 2.0], name="my_const")
# with tf.Session() as sess:
#      print(sess.graph.as_graph_def())

**What’s wrong with constants?**  
**This makes loading graphs expensive when constants are big**  

* **Only use constants for primitive types.**
* **Use variables or readers for more data that requires more memory**

## Variables

In [39]:
# create variables with tf.Variable
s = tf.Variable(2, name="scalar")
m = tf.Variable([[0, 1], [2, 3]], name="matrix")
W = tf.Variable(tf.zeros([784,10]))

Instructions for updating:
Colocations handled automatically by placer.


In [40]:
# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2))
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

**Why tf.constant but tf.Variable?**

* **tf.constant is an op**
* **tf.Variable is a class with many ops**

**tf.Variable holds several ops:**  
x = tf.Variable(...)  
x.initializer # init op  
x.value() # read op  
x.assign(...) # write op  
x.assign_add(...) # and more  

In [41]:
## FailedPreconditionError: Attempting to use uninitialized value Variable
# with tf.Session() as sess:
#     print(sess.run(W)) 

### You have to initialize your variables

#### The easiest way is initializing all variables at once:

In [42]:
with tf.Session() as sess:
     sess.run(tf.global_variables_initializer())

**Initializer is an op. You need to execute it within the context of a session**

#### Initialize only a subset of variables:

In [43]:
a = tf.get_variable("new_a", initializer=tf.constant(2))
b = tf.get_variable("new_b", initializer=tf.constant([[0, 1], [2, 3]]))
with tf.Session() as sess:
    sess.run(tf.variables_initializer([a, b]))

**Initialize a single variable**

In [44]:
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
     sess.run(W.initializer)

**Eval() a variable**

In [45]:
# W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
     sess.run(W.initializer)
     print(W)

<tf.Variable 'Variable_2:0' shape=(700, 10) dtype=float32_ref>


In [46]:
 # W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
     sess.run(W.initializer)
     print(W.eval())    # Similar to print(sess.run(W))

[[-1.3585207  -0.26082855 -0.77772367 ...  0.7638039  -0.78380114
   0.05888113]
 [-0.54085964 -1.3026671  -1.4050846  ... -1.111431    1.0019832
  -0.1288679 ]
 [-1.1959075  -0.31608912 -0.7826985  ...  0.87733245  1.6213993
   0.7859457 ]
 ...
 [ 0.20817828 -0.6878276   0.6815436  ... -0.527968    1.0681759
  -1.6109567 ]
 [ 0.22283703 -0.07138795  0.92810667 ... -0.40445748  1.2574506
   0.07722294]
 [-1.7497178  -0.8770621   0.99389136 ...  0.17650008  1.0534966
  -1.4417505 ]]


**tf.Variable.assign()**

In [47]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
     sess.run(W.initializer)
     print(W.eval())

10


W.assign(100) creates an assign op. That op needs to be executed in a session to take effect.

In [48]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
     sess.run(W.initializer)
     sess.run(assign_op)
     print(W.eval())

100


In [49]:
 # create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")
# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)
with tf.Session() as sess:
     sess.run(my_var.initializer)
     print(sess.run(my_var_times_two)) #what’s the value of my_var now?

4


In [50]:
 # create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")
# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)
with tf.Session() as sess:
     sess.run(my_var.initializer)
     print(sess.run(my_var_times_two)) # the value of my_var now is 4
     print(sess.run(my_var_times_two)) # the value of my_var now is ???

4
8


In [51]:
 # create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")
# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)
with tf.Session() as sess:
     sess.run(my_var.initializer)
     print(sess.run(my_var_times_two)) # the value of my_var now is 4
     print(sess.run(my_var_times_two)) # the value of my_var now is 8
     print(sess.run(my_var_times_two)) # the value of my_var now is 16

4
8
16


**assign_add() and assign_sub()**

In [52]:
my_var = tf.Variable(10)
with tf.Session() as sess:
     sess.run(my_var.initializer)
     # increment by 10
     print(sess.run(my_var.assign_add(10)))
     # decrement by 2
     print(sess.run(my_var.assign_sub(2)))

20
18


**Each session maintains its own copy of variables**

In [53]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))
sess1.close()
sess2.close()

20
8


In [54]:
W = tf.Variable(10)
with tf.Session() as sess1:
    sess1.run(W.initializer)
    print(sess1.run(W.assign_add(10)))
with tf.Session() as sess2:
    sess2.run(W.initializer)
    print(sess2.run(W.assign_sub(2)))

20
8


In [55]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))
print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))
sess1.close()
sess2.close()

20
8
120
-42


##   Control Dependencies

**tf.Graph.control_dependencies(control_inputs)**  
defines which ops should be run first  
your graph g have 5 ops: a, b, c, d, e  
g = tf.get_default_graph()   
with g.control_dependencies([a, b, c]):  
'd' and 'e' will only run after 'a', 'b', and 'c' have executed.  
d =...  
e=...  
 

**Getting to know each other**

## Placeholder

**A quick reminder**  
A TF program often has 2 phases:  
1. Assemble a graph
2. Use a session to execute operations in the graph.  

⇒ Assemble the graph first without knowing the values needed for computation  
Analogy: Define the function f(x, y) = 2 * x + y without knowing value of x or y. x, y are placeholders for the actual values.

 **Why placeholders?**  
 We, or our clients, can later supply their own data when they need to execute the computation.
 

**tf.placeholder(dtype, shape=None, name=None)**

In [56]:
# # create a placeholder for a vector of 3 elements, type tf.float32
# a = tf.placeholder(tf.float32, shape=[3])
# b = tf.constant([5, 5, 5], tf.float32)
# # use the placeholder as you would a constant or a variable
# c = a + b  # short for tf.add(a, b)
## Raise an Error if you run the following code:
## InvalidArgumentError: a doesn’t an actual value
# with tf.Session() as sess:
#     print(sess.run(c))

**Supplement the values to placeholders using a dictionary**

In [57]:
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b  # short for tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [1, 2, 3]})) 
    # the tensor a is the key, not the string ‘a’

[6. 7. 8.]


*tf.placeholder(dtype, **shape=None**, name=None)*  

Quirk:  
shape=None means that tensor of any shape will be accepted as value for placeholder.  

shape=None is easy to construct graphs, but nightmarish for debugging
 

Quirk:  
**shape=None also breaks all following shape inference, which makes many ops not work because they expect certain rank.**

In [58]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
   # use the placeholder as you would a constant or a variable
c = a + b  # Short for tf.add(a, b)
with tf.Session() as sess:
      print(sess.run(c, {a: [1, 2, 3]}))

[6. 7. 8.]


What if want to feed multiple data points in?

In [59]:
# You have to do it one at a time
list_of_values_for_a=[[1,2,3], [4,5,6]]
with tf.Session() as sess:
     for a_value in list_of_values_for_a:
           print(sess.run(c, {a: a_value}))

[6. 7. 8.]
[ 9. 10. 11.]


**You can feed_dict any feedable tensor. Placeholder is just a way to indicate that something must be fed**

**tf.Graph.is_feedable(tensor)**  
True if and only if tensor is feedable.

### Feeding values to TF ops

In [60]:
# create operations, tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)
with tf.Session() as sess:
     # compute the value of b given a is 15
     print(sess.run(b, feed_dict={a: 15}))

45


**Extremely helpful for testing Feed in dummy values to test parts of a large graph**

### The trap of lazy loading

What’s lazy loading?

 Defer creating/initializing an object until it is needed

### Lazy loading Example

In [61]:
# Normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # create the node before executing the graph
writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
     sess.run(tf.global_variables_initializer())
     for _ in range(10):
        sess.run(z)
writer.close()

In [62]:
# Lazy loading    
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
writer = tf.summary.FileWriter('./graphs/lazy_loading', tf.get_default_graph())
with tf.Session() as sess:
     sess.run(tf.global_variables_initializer())
     for _ in range(10):
           sess.run(tf.add(x, y)) # someone decides to be clever to save one line of code
writer.close()

**Both give the same value of z What’s the problem?**

 **tf.get_default_graph().as_graph_def()**  
 **Normal loading**  
     node {  
  name: "Add"  
  op: "Add"  
  input: "x/read"  
  input: "y/read"  
  attr {  
    key: "T"  
    value {  
      type: DT_INT32  
    }  
} }  

 **tf.get_default_graph().as_graph_def() Lazy loading**  
**Lazy loading**  
node {  
  name: "Add_1"  
  op: "Add"  
  ...  
  }  
... node {  
  name: "Add_10"  
  op: "Add"  
  ...  
}  

Node “Add” added 10 times to the graph definition  
Or as many times as you want to compute z  

* **Imagine you want to compute an op thousands, or millions of times!**  
* **Your graph gets bloated Slow to load Expensive to pass around**  
* **One of the most common TF non-bug bugs I’ve seen on GitHub**

### Solution

1. Separate definition of ops from computing/running ops
2. Use Python property to ensure function is also loaded once the first time it is called

Putting it together:  
Let’s build a machine learning model!

**Next class**  
Linear regression  
Control Flow  
tf.data  
Optimizers  
Logistic regression on MNIST Feedback: huyenn@stanford.edu   
Thanks!