In [3]:
import tensorflow as tf
from sklearn import datasets,model_selection

/Users/hhaji/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Command in TensorFlow:
## Constant Function 

In [4]:
deep_learning = tf.constant('Deep Learning')

## The command session is for running

In [5]:
session = tf.Session()

In [6]:
session.run(deep_learning)

b'Deep Learning'

In [7]:
a = tf.constant(2)
b = tf.constant(2)

## Old Version of multiply function was mul

In [8]:
multiply = tf.multiply(a,b)

In [9]:
session.run(multiply)

4

## The first weights (Variable) is used inside of code and the second one is used inside of the graph of TensorFlow (This is for option name)

In [10]:
weights = tf.Variable(tf.random_normal([300, 200], stddev=0.5),
                          name="weights")

In [11]:
weights

<tf.Variable 'weights:0' shape=(300, 200) dtype=float32_ref>

## Assign values to all variables as follows:

In [12]:
init=tf.initialize_all_variables()
session.run(init)
session.run(weights)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


array([[ 0.65177315,  0.37919012,  0.33735713, ...,  0.16024433,
         0.07870616, -0.386781  ],
       [-0.6506289 ,  0.3482424 ,  0.35275257, ..., -0.85527575,
        -0.46937022, -0.6499083 ],
       [ 0.05714766,  0.32699257, -0.00587499, ...,  0.05902446,
        -0.55410236,  0.2765769 ],
       ...,
       [-0.5184843 ,  0.12025747,  0.33167204, ..., -0.46220484,
         0.21845046, -0.06007111],
       [ 0.6656865 , -0.30584526, -0.15435487, ...,  0.1585495 ,
         0.30617106,  0.2866825 ],
       [-0.14727443,  0.946468  ,  0.63563216, ...,  0.5182311 ,
         0.6637884 , -0.43646932]], dtype=float32)

## Compare the Value of Weights after running two times of the same code

In [13]:
session.run(weights)

array([[ 0.65177315,  0.37919012,  0.33735713, ...,  0.16024433,
         0.07870616, -0.386781  ],
       [-0.6506289 ,  0.3482424 ,  0.35275257, ..., -0.85527575,
        -0.46937022, -0.6499083 ],
       [ 0.05714766,  0.32699257, -0.00587499, ...,  0.05902446,
        -0.55410236,  0.2765769 ],
       ...,
       [-0.5184843 ,  0.12025747,  0.33167204, ..., -0.46220484,
         0.21845046, -0.06007111],
       [ 0.6656865 , -0.30584526, -0.15435487, ...,  0.1585495 ,
         0.30617106,  0.2866825 ],
       [-0.14727443,  0.946468  ,  0.63563216, ...,  0.5182311 ,
         0.6637884 , -0.43646932]], dtype=float32)

## If we want to prevent updating the variable, then we use option trainable=False

In [14]:
 weights = tf.Variable(tf.random_normal([300, 200], stddev=0.5),
                          name="weights", trainable=False)

## Placeholder keeps an amount temporarily
## Note that in y=ax+b, a and b are variable while x is a placeholder

In [15]:
x = tf.placeholder(tf.float32, name="x", shape=[None, 784])
W = tf.Variable(tf.random_uniform([784,10], -1, 1), name="W")
multiply = tf.matmul(x, W)

## Load Data from Datasets

In [16]:
data=datasets.load_digits()

In [17]:
data

{'DESCR': "Optical Recognition of Handwritten Digits Data Set\n===================================================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttp://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels ar

### Check a column named data

In [20]:
xx=data.data

In [21]:
xx

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [22]:
y=data.target

In [23]:
y

array([0, 1, 2, ..., 8, 9, 8])

## Convert Categorical Variable to Dummy Variable

In [24]:
yt=tf.one_hot(y, depth=10)

In [25]:
yt=session.run(yt)
yt

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

## Split Data to Training and Test Sets

In [27]:
x_tr,x_te,y_tr,y_te=model_selection.train_test_split(xx,yt)

### Note that nn is a module in Tensorflow which contains activation functions
### get_variable uses the same variable anytime we run a layer or a function and it does not produce a new variable! Check Page 62 PDF of the book!

## Now we define the output function of any layer

In [28]:
def layer(x,w_shape,b_shape):
    w=tf.get_variable(name='w',shape=w_shape,initializer=tf.random_uniform_initializer())
    b=tf.get_variable(name='b',shape=b_shape,initializer=tf.random_uniform_initializer())
    return tf.nn.relu(tf.matmul(x,w)+b)

## variable_scope is a command to use old variable on a special domain

## if we run code two times, we face with an Error, then one can restart Jupyter or
## we can use the option  reuse=True inside of tf.variable_scope('hidden_0')

# Now we define layers and the number of Neruns

In [29]:
def neron(x):
    with tf.variable_scope('hidden_0'):
        hidden_0=layer(x,[64,128],128)
    with tf.variable_scope('hidden_1'):
        hidden_1=layer(hidden_0,[128,64],64)
    with tf.variable_scope('hidden_2'):
        hidden_2=layer(hidden_1,[64,32],32)
    with tf.variable_scope('output'):
        output=layer(hidden_2,[32,10],10)
    return output

In [30]:
def loss(output,y):
    entropy=tf.nn.softmax_cross_entropy_with_logits(logits=output,labels=y)
    loss=tf.reduce_mean(entropy)
    return loss

In [31]:
def optimizer(cost):
    optimize=tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost,global_step=global_step)
#     optimize=tf.train.AdagradOptimizer(learning_rate=learning_rate).minimize(cost)
    return optimize

In [32]:
def evaluate(output,y):
    # Output of the equal function is a boolean vector (True-Fale)
    predict=tf.equal(tf.argmax(output,1),tf.argmax(y,1))
    # cast function convert a boolean to a 0-1 vector
    ac=tf.reduce_mean(tf.cast(predict,tf.float32))
    return ac

x=tf.placeholder('float',[None,64])
y=tf.placeholder('float',[None,10])
epoch=20000
learning_rate=0.1
global_step=tf.Variable(0,name='global_step',trainable=False)

In [33]:
output=neron(x)
cost=loss(output,y)
train=optimizer(cost)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [34]:
eval_ = evaluate(output, y)
init_op = tf.global_variables_initializer()
session.run(init_op)
feed_dict1 = {x : x_tr, y : y_tr}
feed_dict2 = {x : x_te, y : y_te}

In [35]:
for i in range(epoch):
    session.run(train,feed_dict1)

print('accuracy _train: ',session.run(eval_,feed_dict1))
print('accuracy _test: ',session.run(eval_,feed_dict2))

accuracy _train:  0.10616184
accuracy _test:  0.07777778


In [36]:
# summary_op = tf.summary.merge_all()
# summary_writer = tf.summary.FileWriter("logistic_logs/", graph_def=session.graph_def)
# summary_str = session.run(summary_op,feed_dict=feed_dict1)
# summary_writer.add_summary(summary_str, session.run(global_step))
# saver.save(session, "logistic_logs/model-checkpoint",global_step=global_step)